"""empty message

Revision ID: 22343b63da28
Revises: 891e11819724
Create Date: 2022-06-14 16:21:01.093409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22343b63da28'
down_revision = '891e11819724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('reverse', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'reverse')
    # ### end Alembic commands ###
