"""empty message

Revision ID: 46e2549de7a3
Revises: 891e11819724
Create Date: 2022-06-14 14:56:00.897211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e2549de7a3'
down_revision = '891e11819724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('token', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'token')
    # ### end Alembic commands ###
