"""empty message

Revision ID: 4d81c2a3e838
Revises: 891e11819724
Create Date: 2022-05-24 17:27:07.671034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d81c2a3e838'
down_revision = '891e11819724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('ai', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'ai')
    # ### end Alembic commands ###
