"""empty message

Revision ID: 658117089a00
Revises: 46e2549de7a3
Create Date: 2022-06-28 10:29:02.179547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658117089a00'
down_revision = '46e2549de7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('n_players', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'n_players')
    # ### end Alembic commands ###
