"""empty message

Revision ID: 891e11819724
Revises: 
Create Date: 2022-03-19 19:40:45.194091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891e11819724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_player', sa.Integer(), nullable=False),
    sa.Column('top_card', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    players = op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ai', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_player',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('hand', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(players, [
        {'name': 'Testspieler 1', "ai":False},
        {'name': 'Testspieler 2', "ai":False},
        {'name': 'Testspieler 3', "ai":False},
        {'name': 'Testspieler 4', "ai":False},
        {'name': 'Testspieler 5', "ai":False},
        {'name': 'Testspieler 6', "ai":False},
        {'name': 'Testspieler 7', "ai":False},
        {'name': 'Testspieler 8', "ai":False},
        {'name': 'Testspieler 9', "ai":False},
        {'name': 'Testspieler 10', "ai":False}
    ])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_player')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
