"""empty message

Revision ID: b65f5efce258
Revises: 55cc8c084cc0
Create Date: 2022-06-14 16:16:22.057972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b65f5efce258'
down_revision = '55cc8c084cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        status_enum = sa.Enum('NOT_STARTED', 'STARTED',
                              'FINISHED', name='status')
        status_enum.create(connection)
        op.add_column('games', sa.Column('state', status_enum, nullable=False))
    else:
        op.add_column('games', sa.Column('state', sa.Enum(
            'NOT_STARTED', 'STARTED', 'FINISHED', name='status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'state')
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        op.execute('DROP TYPE status;')
    # ### end Alembic commands ###
